### ISSUE TITLE
While hiding the target div or parent div then loading is still visible. Please provide the solution.

### ISSUE THREAD

**Issue by KA24956T** [gasparesganga/jquery-loading-overlay#39] opened 2018-12-24 11:18 UTC
While hiding the target div or parent div then loading is still visible. Please provide the solution.

**Comment by gasparesganga** [comment] 2018-12-24 13:40
Please provide some example code which shows the behaviour, then I will eventually be able to work out a solution

**Comment by gasparesganga** [comment] 2018-12-31 08:35
Any update?

**Comment by gasparesganga** [comment] 2019-01-14 09:10
Nothing? Then I guess you fixed something on your side and this wasn't caused by LoadingOverlay... I'm closing this...

**Closed as completed by gasparesganga** 2019-01-14 09:10 UTC
Labels: invalid
