### ISSUE TITLE
Uncaught TypeError: Cannot read property 'extend' of undefined

### ISSUE THREAD

**Issue by joshlobe** [gasparesganga/jquery-loading-overlay#12] opened 2017-01-27 08:38 UTC
Hello, I just started using your plugin and love the light-weight code.  Thanks!!

I tried using the progressbar addition; but ran into an issue.  I took the code off the cdn, and included it into a single file to keep it local.  I have a slew of other stuff running, so it's entirely possible something else is interfering.  jQuery is not my strongest language, and I'm a bit lost.

Any assistance would be greatly appreciated.  Screenshot is attached.  This is happening in all of my browsers (chrome, firefox, opera, and safari).

Thank you.

![capture](https://cloud.githubusercontent.com/assets/1818478/22364832/135d9e32-e442-11e6-82a9-b9797bd9b474.PNG)

**Comment by gasparesganga** [comment] 2017-01-27 09:14
For testing purposes you should try to run the same code using the single js files, not merged into a single one. This way you should be able to identify the exact file that generates the problem and at what line.

I I have to guess judging from your screenshot, I would say jQuery is not properly loaded before you try to initialize a LoadingOverlayProgress.

Anyways, could you post the relevant code that generates the problem?

**Comment by joshlobe** [comment] 2017-01-27 10:55
I do love a responsive developer!

Well, it's in a WordPress site, so jquery is loaded as a dependency to the two files you've written.  I'm sorry I can't give you the page; it's behind a paid membership platform.  I'll try tomorrow (it's late here) to replicate on a public site where I can share the link.

In the meantime, here is the updated screenshot:

![capture](https://cloud.githubusercontent.com/assets/1818478/22368556/1821a108-e455-11e6-9159-e0413cac2399.PNG)

**Comment by gasparesganga** [comment] 2017-01-27 11:02
I've just released a new bugfix version of this plugin and I am pretty sure it works fine, I test everything before every release. I am incline to think it's something related to your website configuration.
As I wrote before, that error message leads to think whether jQuery has been already defined or not. Extra Progress uses `$.extend()` when initialized, so that *undefined* could be exactly `$` (jQuery)!

**Comment by joshlobe** [comment] 2017-01-27 11:08
Understood.  I'll get it on a public site tomorrow and see if the issue persists.  I'll update back here as soon as I make some progress.

Thank you.

**Comment by gasparesganga** [comment] 2017-02-21 15:34
No updates about that?
Was the cause the one I hinted?

**Comment by gasparesganga** [comment] 2017-02-27 16:45
After one month without any reply, I'm assuming I was right about the missing jQuery library...
I'm closing this.

**Closed as completed by gasparesganga** 2017-02-27 16:45 UTC
Labels: can't reproduce
